// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWps-sJ15vOo-4MFe1YVS2ox8PR7MTqIk',
    appId: '1:422530467068:web:72c90d4a5a869f90b80379',
    messagingSenderId: '422530467068',
    projectId: 'masterclass-8fea1',
    authDomain: 'masterclass-8fea1.firebaseapp.com',
    storageBucket: 'masterclass-8fea1.appspot.com',
    measurementId: 'G-1074BVKVS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA5RYpseGeNnThliBSsP1UAnl6LgESjQQ',
    appId: '1:422530467068:android:23f598cafe7fa990b80379',
    messagingSenderId: '422530467068',
    projectId: 'masterclass-8fea1',
    storageBucket: 'masterclass-8fea1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHu8kLomNXeSbfVBJDUC4__sr4WNLb6Q',
    appId: '1:422530467068:ios:4a435812f2a75fd3b80379',
    messagingSenderId: '422530467068',
    projectId: 'masterclass-8fea1',
    storageBucket: 'masterclass-8fea1.appspot.com',
    iosClientId: '422530467068-11c1sjauoo4815nafhpbqq44gbn8gdt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsHu8kLomNXeSbfVBJDUC4__sr4WNLb6Q',
    appId: '1:422530467068:ios:4a435812f2a75fd3b80379',
    messagingSenderId: '422530467068',
    projectId: 'masterclass-8fea1',
    storageBucket: 'masterclass-8fea1.appspot.com',
    iosClientId: '422530467068-11c1sjauoo4815nafhpbqq44gbn8gdt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.masterclass',
  );
}
